#!name=安徽掌上10000
#!desc=某些APP要清除缓存或者重新安装拦截广告才会生效！
#!author=奶思
#!category=奶思的模块
#!homepage=https://github.com/fmz200/wool_scripts
#!raw-url=https://github.com/fmz200/wool_scripts/raw/main/Surge/module/split/partA/AnhuiZhangShang10000.sgmodule
#!tg-channel=https://t.me/inaisi

[URL Rewrite]
^https?:\/\/www\.ahzs10000\.com\/palmhall\/client\/base\/newVerson_getStartUp\.action - reject-dict

[MITM]
hostname = %APPEND% www.ahzs10000.com

