#!name=宝宝树孕育
#!desc=某些APP要清除缓存或者重新安装拦截广告才会生效！
#!author=奶思
#!category=奶思的模块
#!homepage=https://github.com/fmz200/wool_scripts
#!raw-url=https://github.com/fmz200/wool_scripts/raw/main/Surge/module/split/partB/BabyTreeParenting.sgmodule
#!tg-channel=https://t.me/inaisi

[URL Rewrite]
^https?:\/\/aimg\.babytreeimg\.com\/group1\/M00\/*\/*\/.*.jpg - reject-dict

# 开屏广告 感谢【alist.choc.ga】分享
^https?:\/\/plough\.babytree\.com\/plough\.do - reject-dict

# 弹窗广告 感谢【Ron】分享
^https?:\/\/mapiweb\.babytree\.com\/newapi\/luban\/behavior\/receive - reject-dict

^https?:\/\/go\.babytree\.com\/go_pregnancy\/api\/index_activity\/get_app_index_activity - reject-dict

^https?:\/\/go\.babytree\.com\/go_tool\/api\/feeding_record\/get_home_banner_info - reject-dict

[MITM]
hostname = %APPEND% aimg.babytreeimg.com, plough.babytree.com, mapiweb.babytree.com, go.babytree.com

