#!name=北京银行
#!desc=某些APP要清除缓存或者重新安装拦截广告才会生效！
#!author=奶思
#!category=奶思的模块
#!homepage=https://github.com/fmz200/wool_scripts
#!raw-url=https://github.com/fmz200/wool_scripts/raw/main/Surge/module/split/partB/BankOfBeijing.sgmodule
#!tg-channel=https://t.me/inaisi

[URL Rewrite]
^https?:\/\/cdnmobibank\.bankofbeijing\.com\.cn\/cdn\/MarketingCloud\/.+\/.+\/99_1\/.+\.jpg - reject-dict

[MITM]
hostname = %APPEND% cdnmobibank.bankofbeijing.com.cn

