#!name=半月谈
#!desc=某些APP要清除缓存或者重新安装拦截广告才会生效！
#!author=奶思
#!category=奶思的模块
#!homepage=https://github.com/fmz200/wool_scripts
#!raw-url=https://github.com/fmz200/wool_scripts/raw/main/Surge/module/split/partB/BanYueTan.sgmodule
#!tg-channel=https://t.me/inaisi

[URL Rewrite]
# 开屏广告
^https?:\/\/www\.banyuetanapp\.com\/byt-api\/ad\/getAdvertList\?adSpaceId=100000002 - reject-dict

[MITM]
hostname = %APPEND% www.banyuetanapp.com

